### ISSUE TITLE
Show all tweets created by loklak with rich content attachments within the search results.

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#100]
While the search results should be identical to twitter search result views, we want to make use of our own abilities and show the rich content of special tweets that are developed in https://github.com/loklak/loklak_webclient/issues/63

This means, you should share your work to visualize the rich-content tweets. This affects the following formats:
- identify and attach exact geographic coordinates and maps
- attach video and/or audio content
- attach larger texts with simple markdown (i.e. https://guides.github.com/features/mastering-markdown/) as used in github or maybe wikitext, code citations (with code pretty-print) and other typical text rendering
- attach better images (i.e. animated gif or images with EXIF data attached)

**Comment by Orbiter** [comment]
Are there already fine-specified issues for this umbrella-feature? If not, please open these issues.
You get support for the content of cross-posted tweets by the backend. There will be servlets to create preview-images for rich tweets:
- for tweets with locations: https://github.com/loklak/loklak_server/issues/39
- for large texts with markdown: https://github.com/loklak/loklak_server/issues/40
- for image attachments: https://github.com/loklak/loklak_server/issues/42

please add the reference to each loklak_server feature to all sub-features of this issue.

**Comment by Orbiter** [comment]
see also: https://github.com/loklak/loklak_webclient/issues/97

**Comment by Orbiter** [comment]
Here is the process on how to show rich-text tweets, which is regulated with the message form convention for rich-text tweets in https://github.com/loklak/loklak_server/issues/66:
- for each message: check if the string `\n***\n` appears. If it appears, the message is a rich text tweet.
- separate the text into two parts: the text in front of `\n***\n` is the normal tweet message which shall be displayed as such. The text behind `\n***\n` is the rich text.
- the rich text must be displayed with a rich-text-to-html library below the message, not with the markdown servlet! We want to show this in a nice format in our own interface. The usage of the markdown servlet is only for cross-posting to twitter!

**Comment by mariobehling** [comment]
@fuksi Any update on this issue? What are the next steps? Does this have to be moved to M3?

**Comment by fuksi** [comment]
I was slow on this. I just asked on gitter for an example query since, although the instructions are clear, it can't be checked without real data.  

I'm not expecting is a challenge here. This will be implemented in this week as soon as an example query is available.

**Comment by Orbiter** [comment]
Here are the methods for each type of rich tweet:

for locations, see https://github.com/loklak/loklak_server/issues/39
User the `location_source="USER"` when pushing them to loklak and select them with `/location=USER` and `/location=1.2,3.4,5.6,7.8,USER`

(more to come)

**Comment by fuksi** [comment]
This issue is heavily based on the process of other, let's track it here:

- [ ] based of #93  identify and attach exact geographic coordinates and maps
- [ ] based of #97 attach video and/or audio content
- [ ] based of #94 attach larger texts with simple markdown (i.e. https://guides.github.com/features/mastering-markdown/) as used in github or maybe wikitext, code citations (with code pretty-print) and other typical text rendering

**Comment by mariobehling** [comment]
Postponing this feature and reopen issue when needed.
